"""refresh tokens opaque with family v2

Revision ID: 66d4d55d3633
Revises: b732323671e1
Create Date: 2026-09-29 15:42:32.668866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66d4d55d3633'
down_revision: Union[str, Sequence[str], None] = 'b732323671e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('refresh_token_hash', sa.String(length=64), nullable=False))
    op.add_column('refreshtokens', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('refreshtokens', sa.Column('family_id', sa.Uuid(), nullable=False))
    op.add_column('refreshtokens', sa.Column('family_expires_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_index(op.f('ix_refreshtokens_jti'), table_name='refreshtokens')
    op.create_index(op.f('ix_refreshtokens_family_id'), 'refreshtokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refreshtokens_refresh_token_hash'), 'refreshtokens', ['refresh_token_hash'], unique=True)
    op.drop_column('refreshtokens', 'jti')
    op.drop_column('refreshtokens', 'expire_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refreshtokens', sa.Column('expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('refreshtokens', sa.Column('jti', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_refreshtokens_refresh_token_hash'), table_name='refreshtokens')
    op.drop_index(op.f('ix_refreshtokens_family_id'), table_name='refreshtokens')
    op.create_index(op.f('ix_refreshtokens_jti'), 'refreshtokens', ['jti'], unique=True)
    op.drop_column('refreshtokens', 'family_expires_at')
    op.drop_column('refreshtokens', 'family_id')
    op.drop_column('refreshtokens', 'expires_at')
    op.drop_column('refreshtokens', 'refresh_token_hash')
    # ### end Alembic commands ###
